create table if not exists public.devices (
  id text primary key,
  status text not null default 'OFFLINE',
  last_seen timestamptz,
  feed_now bool not null default false
);

create table if not exists public.schedules (
  id int8 primary key,
  feed_time time,
  status text not null default 'Pending',
  enabled bool not null default false,
  completed bool not null default false
);

create table if not exists public.feed_logs (
  id int8 generated by default as identity primary key,
  feed_type text not null,
  fed_at timestamptz not null default now()
);

insert into public.devices (id, status, last_seen, feed_now)
values ('FEEDER001', 'OFFLINE', now(), false)
on conflict (id) do nothing;

insert into public.schedules (id, feed_time, status, enabled, completed)
values
  (1, null, 'Pending', false, false),
  (2, null, 'Pending', false, false),
  (3, null, 'Pending', false, false)
on conflict (id) do nothing;

alter table public.devices enable row level security;
alter table public.schedules enable row level security;
alter table public.feed_logs enable row level security;

drop policy if exists "Allow public device access" on public.devices;
create policy "Allow public device access"
on public.devices for all
to anon
using (true)
with check (true);

drop policy if exists "Allow public schedule access" on public.schedules;
create policy "Allow public schedule access"
on public.schedules for all
to anon
using (true)
with check (true);

drop policy if exists "Allow public feed log access" on public.feed_logs;
create policy "Allow public feed log access"
on public.feed_logs for all
to anon
using (true)
with check (true);

-- In Supabase Dashboard > Database > Replication, enable realtime for:
-- devices, schedules, feed_logs.
